```{r}
glmpoiscomplet <- glm(docvis~female+year+age+hsat+handdum+handper+hhninc+hhkids+educ+
                        married+working+bluec+whitec+self+public+addon+offset(log(ancov)),
                      family = poisson, data = med_train_adjust)

(summaryglmpoiscomplet <- summary(glmpoiscomplet))

### Coefficient et écart-type pour a)
summaryglmpoiscomplet$coefficients[,c(1,2)]
```

```{r}
qchisq(0.99,1) # Valeur de référence 6,634897

anova(glmpoiscomplet) # Le plus petit est working avec 0.63

# Modèle sans working
glmpois1 <- glm(docvis~female+year+age+hsat+handdum+handper+hhninc+hhkids+educ+
                  married+bluec+whitec+self+public+addon+offset(log(ancov)),
                family = poisson, data = med_train_adjust)

anova(glmpois1) # Le plus petit est whitec avec 0.00

# Modèle sans whitec et working
glmpois2 <- glm(docvis~female+year+age+hsat+handdum+handper+hhninc+hhkids+educ+
                  married+bluec+self+public+addon+offset(log(ancov)),
                family = poisson, data = med_train_adjust)

anova(glmpois2) # Le plus petit est handum avec 1.17

# Modèle sans whitec, working et handum
glmpois3 <- glm(docvis~female+year+age+hsat+handper+hhninc+hhkids+educ+
                  married+bluec+self+public+addon+offset(log(ancov)),
                family = poisson, data = med_train_adjust)

anova(glmpois3) # Le plus petit est addon avec 1.78

# Modèle sans whitec, working, handum et addon
glmpois4 <- glm(docvis~female+year+age+hsat+handper+hhninc+hhkids+educ+
                  married+bluec+self+public+offset(log(ancov)),
                family = poisson, data = med_train_adjust)

anova(glmpois4) # Le plus petit est public avec 4.72

# Modèle courant sans whitec, working, handum, addon et public
glmpoiscourant <- glm(docvis~female+year+age+hsat+handper+hhninc+hhkids+educ+
                        married+bluec+self+offset(log(ancov)),
                      family = poisson, data = med_train_adjust)

anova(glmpoiscourant)
```
c)
```{r}
# Pearson
summary(glmpoiscourant)
qchisq(0.99,length(med_train_adjust)-length(summary(glmpoiscourant)$coefficients[,1])+1) # Référence 20.09024 avec n-p' degré de liberté
sum(residuals(glmpoiscourant,type = "pearson")^2)

# Déviance
summary(glmpoiscourant)$deviance # Selon les notes de cours page 155

# AIC
summary(glmpoiscourant)$aic

df <- data.frame("Modèle" = "courant", "Pearson" = sum(residuals(glmpoiscourant,type = "pearson")^2), "Déviance" = summary(glmpoiscourant)$deviance, "AIC" = summary(glmpoiscourant)$aic)
```

d )

```{r}
# Estimation des paramètres + VaR (normale et poisson)
predict_75_a_84 <- predict(glmpoiscourant,med_valid[med_valid$ID>=1075 & med_valid$ID<=1084,],
                           type = "response", se.fit = TRUE)

VaR0.99 <- qnorm(0.99, predict_75_a_84$fit, predict_75_a_84$se.fit)
VaR0.99_qpois <- qpois(0.99, predict_75_a_84$fit)

moy_et_VaR <- data.frame("Moyenne" = predict_75_a_84$fit,
                     "Écart-type" = predict_75_a_84$se.fit,
                     "VaR0.99_norm" = VaR0.99, 
                     "VaR0.99_pois" = VaR0.99_qpois)
moy_et_VaR


```
e)

```{r}
eta_75_a_84 <- predict(glmpoiscourant,med_valid[med_valid$ID>=1075 & med_valid$ID<=1084,],
                          type = "link", se.fit = TRUE)
# On inverse tout de suite les bornes pour 'eta', puisqu'on veut fournir un intervalle de confiance pour 'mu'
int_conf_eta <- data.frame("lower" = eta_75_a_84$fit + qnorm(0.975) * eta_75_a_84$se.fit,
                       "fit" = eta_75_a_84$fit,
                       "upper" = eta_75_a_84$fit + qnorm(0.025) * eta_75_a_84$se.fit)
int_conf_lambda <- exp(int_conf_eta)
round(exp(-int_conf_lambda), 5) # IC sur la probabilité P(Yi = 0)

```
f)
```{r}
## Graphique fonction de masse de probabilité estimé

lambda_94_et_217 <- predict(glmpoiscourant,med_valid[med_valid$ID ==1094 | med_valid$ID ==1217,],
                            type = "response")/med_valid[med_valid$ID ==1094 | med_valid$ID ==1217, c('ancov')]

# La division est pour mettre ça sur une échelle annuelle

plot(1:20,dpois(1:20,lambda = lambda_94_et_217[1]), type = "h",
     xlab = "Nombre annuel de consultation",
     ylab = "Probabilité")
     #sub = "Fonction de masse de probabilité pour le nombre annuel de consultation estimées pour l'ID 1094")

plot(1:25,dpois(1:25,lambda = lambda_94_et_217[2]), type = "h",
     xlab = "Nombre annuel de consultation",
     ylab = "Probabilité")
     #sub = "Fonction de masse de probabilité pour le nombre annuel de consultation estimées pour l'ID 1217")

```
g)

```{r}
# Pearson
hist(residuals(glmpoiscourant,type = "pearson"))

# Anscombe revoir pour être sur
hatmu <- fitted(glmpoiscourant)
anscombe <- 1.5*((med_train_adjust$docvis)^(2/3)-hatmu^(2/3))/hatmu^(1/6)
hist(anscombe)

# Déviance
hist(residuals(glmpoiscourant,type = "deviance"))
```

